# CI 项目
name: QCA-6.12-VIKINGYFY

on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用换行符隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean

permissions:
  contents: write

jobs:
  config:
    name: ${{ matrix.CONFIG }}

    strategy:
      fail-fast: false

    matrix:
      CONFIG: [IPQ60XX-NOWIFI, IPQ60XX-WIFI]
      SOURCE: [VIKINGYFY/immortalwrt]
      BRANCH: [main]

    uses: ./.github/workflows/WRT-CORE.yml

    with:
      WRT_CONFIG: ${{ matrix.CONFIG }}
      WRT_THEME: argon
      WRT_NAME: WH
      WRT_SSID: 1006
      WRT_IP: 192.168.68.1

      WRT_REPO: https://github.com/${{ matrix.SOURCE }}.git
      WRT_BRANCH: ${{ matrix.BRANCH }}
      WRT_SOURCE: ${{ matrix.SOURCE }}

      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST }}

      CI_NAME: ${{ github.workflow }}

    secrets:
      WRT_WORD: ${{ secrets.WRT_WORD }}
